### ISSUE TITLE
Broken `no_std` support

### ISSUE THREAD

**Issue by ElouanPetereau** [neuromorphicsystems/sgp4#11]
Hi,

I am using your crate as part as a `no_std` project without any `default-features` and only the `libm` feature.    
I wanted to update my dependencies to the latest version of your crate (`2.0`) but it seems that it is not `no_std` ready anymore since you added the `thiserror` dependency.

Are you aware of this problem and, if not, do you plan to keep the support of `no_std` for your crate?

Here is the result of a build with the `--no-default-features --features libm` arguments:
```shell
    Checking sgp4 v2.0.0 (/home/elouan/Workspaces/Git_Workspace/sgp4)
error[E0433]: failed to resolve: use of undeclared crate or module `std`
 --> src/gp.rs:3:1
  |
3 | pub enum Error {
  | ^^^ use of undeclared crate or module `std`
  |
help: consider importing this module
  |
1 + use core::error;
  |
help: if you import `error`, refer to it directly
  |
3 | pub enum Error {
  |

error[E0433]: failed to resolve: use of undeclared crate or module `std`
  --> src/tle.rs:17:1
   |
17 | pub enum ErrorWhat {
   | ^^^ use of undeclared crate or module `std`
   |
help: consider importing this module
   |
1  + use core::error;
   |
help: if you import `error`, refer to it directly
   |
17 | pub enum ErrorWhat {
   |

error[E0433]: failed to resolve: use of undeclared crate or module `std`
  --> src/tle.rs:60:1
   |
60 | pub enum ErrorLine {
   | ^^^ use of undeclared crate or module `std`
   |
help: consider importing this module
   |
1  + use core::error;
   |
help: if you import `error`, refer to it directly
   |
60 | pub enum ErrorLine {
   |

error[E0433]: failed to resolve: use of undeclared crate or module `std`
  --> src/tle.rs:74:1
   |
74 | pub struct Error {
   | ^^^ use of undeclared crate or module `std`
   |
help: consider importing this module
   |
1  + use core::error;
   |
help: if you import `error`, refer to it directly
   |
74 | pub struct Error {
   |

error[E0433]: failed to resolve: use of undeclared crate or module `std`
   --> src/tle.rs:501:1
    |
501 | pub struct DatetimeToMinutesSinceEpochError {
    | ^^^ use of undeclared crate or module `std`
    |
help: consider importing this module
    |
1   + use core::error;
    |
help: if you import `error`, refer to it directly
    |
501 | pub struct DatetimeToMinutesSinceEpochError {
    |

error[E0433]: failed to resolve: use of undeclared crate or module `std`
   --> src/tle.rs:511:1
    |
511 | pub enum MinutesSinceEpochToDatetimeError {
    | ^^^ use of undeclared crate or module `std`
    |
help: consider importing this module
    |
1   + use core::error;
    |
help: if you import `error`, refer to it directly
    |
511 | pub enum MinutesSinceEpochToDatetimeError {
    |

error[E0433]: failed to resolve: use of undeclared crate or module `std`
  --> src/lib.rs:90:1
   |
90 | pub enum KozaiElementsError {
   | ^^^ use of undeclared crate or module `std`
   |
help: consider importing this module
   |
49 + use core::error;
   |
help: if you import `error`, refer to it directly
   |
90 | pub enum KozaiElementsError {
   |

error[E0433]: failed to resolve: use of undeclared crate or module `std`
   --> src/lib.rs:101:1
    |
101 | pub struct OutOfRangeEpochEccentricity(pub f64);
    | ^^^ use of undeclared crate or module `std`
    |
help: consider importing this module
    |
49  + use core::error;
    |
help: if you import `error`, refer to it directly
    |
101 | pub struct OutOfRangeEpochEccentricity(pub f64);
    |

error[E0433]: failed to resolve: use of undeclared crate or module `std`
   --> src/lib.rs:105:1
    |
105 | pub enum ElementsError {
    | ^^^ use of undeclared crate or module `std`
    |
help: consider importing this module
    |
49  + use core::error;
    |
help: if you import `error`, refer to it directly
    |
105 | pub enum ElementsError {
    |

error[E0433]: failed to resolve: use of undeclared crate or module `std`
   --> src/lib.rs:104:10
    |
104 | #[derive(thiserror::Error, Debug, Clone)]
    |          ^^^^^^^^^^^^^^^^ use of undeclared crate or module `std`
    |
    = note: this error originates in the derive macro `thiserror::Error` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this module
    |
49  + use core::error;
    |
help: if you import `error`, refer to it directly
    |
104 | #[derive(thiserror::Error, Debug, Clone)]
    |

For more information about this error, try `rustc --explain E0433`.
error: could not compile `sgp4` (lib) due to 10 previous errors

```

**Comment by aMarcireau** [comment]
Hi @ElouanPetereau,

Thanks for the feedback! I did not realise that thiserror was not no-std. I just published a new version (2.1.0) without thiserror. Can you let me know if you run into other issues with the new version?

**Comment by ElouanPetereau** [comment]
Hi,

Yes, thank you for the quick answer and fix!

Unfortunately there is still a problem when using the crate with the `libm` feature on a `std` environment.    
I fixed it in the [sgp4!12 ](https://github.com/neuromorphicsystems/sgp4/pull/12) pull request in which I also added CI jobs to test for `std` and `no_std` support.

**Comment by aMarcireau** [comment]
Fixed by PR #12.
